storage: /verdaccio/storage
plugins: ./plugins

# Configuration des logs
logs:
  - { type: stdout, format: pretty, level: http }

# Configuration de la durée de vie du cache (jamais révoqué)
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: -1
    fail_timeout: 0s
    cache_timeout: 0s

packages:
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

# Authentification désactivée pour simplifier
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

web:
  enable: true
  title: Verdaccio Private Registry
